import logging

from django.core.management import BaseCommand

from apps.contacts.models import Contact


class Command(BaseCommand):
    def add_arguments(self, parser):
        parser.add_argument(
            "--is-only-auto-generated",
            help="Delete only autogenerated humans",
            action="store_true",
        )
        parser.add_argument("--all", type=str, help="Delete all contacts!", default="")

    def handle(self, *args, **options):
        is_only_auto_generated: bool = options["is_only_auto_generated"]
        del_all: str = options["all"]

        logger = logging.getLogger("django")

        queryset = Contact.objects.all()

        logger.info(f"Current amount of humans before: {queryset.count()}")

        queryset_for_delete = queryset
        if del_all == "all":
            queryset_for_delete.all().delete()

        if is_only_auto_generated:
            logger.info("Delete only auto generated animals")
            queryset_for_delete = queryset_for_delete.filter(is_auto_generated=True)

        total_deleted, details = queryset_for_delete.delete()
        logger.info(f"Total deleted: {total_deleted}, details: {details}")

        logger.info(f"Current amount of humans after: {queryset.count()}")
